In [1]:
import numpy as np

In [ ]:
# Ejercicio 1

# Actividades
# 1. Convierte la lista en un array de NumPy y reorganízalo como una matriz de 4 × 6.
# 2. Muestra su tipo de dato, número de dimensiones y forma.
# 3. Calcula el total vendido en cada turno y el total vendido de cada producto.
# 4. Identifica el turno con mayor cantidad total de ventas.
# 5. Obtén una copia con todas las ventas incrementadas en 2 unidades y verifica que la matriz original no cambió.

ventas = [18, 12, 25, 10, 8, 15,
          20, 14, 22, 13, 11, 17, 
          16, 19, 27, 9, 12, 18, 
          24, 17, 21, 15, 10, 20]


ventas_matriz = np.array(ventas)
# 1
ventas_matriz= ventas_matriz.reshape(4,6)
print(ventas_matriz)
ventas_matriz.shape
print('-' * 100)
# 2
print(ventas_matriz.dtype) # tipo de dato
print(ventas_matriz.ndim) # nro de dimensin
print(ventas_matriz.shape)  # fila x columna
print('-' * 100)
# 3
ventas_total_turno = ventas_matriz.sum(axis = 1) # suma de columnas
print(ventas_total_turno)
print('-' * 100)

ventas_total_producto = ventas_matriz.sum(axis = 0) # suma de filas
print(ventas_total_producto)
print('-' * 100)

# 4
print(ventas_total_turno.argmax())
print('-' * 100)

# 5
ventas_incrementadas = ventas_matriz + 2
print(ventas_matriz)
print('-' * 100)
print(ventas_incrementadas)
print('-' * 100)


[[18 12 25 10  8 15]
 [20 14 22 13 11 17]
 [16 19 27  9 12 18]
 [24 17 21 15 10 20]]
----------------------------------------------------------------------------------------------------
int64
2
(4, 6)
----------------------------------------------------------------------------------------------------
[ 88  97 101 107]
----------------------------------------------------------------------------------------------------
[78 62 95 47 41 70]
----------------------------------------------------------------------------------------------------
3
----------------------------------------------------------------------------------------------------
[[18 12 25 10  8 15]
 [20 14 22 13 11 17]
 [16 19 27  9 12 18]
 [24 17 21 15 10 20]]
----------------------------------------------------------------------------------------------------
[[20 14 27 12 10 17]
 [22 16 24 15 13 19]
 [18 21 29 11 14 20]
 [26 19 23 17 12 22]]
------------------------------------------------------------------------------------

In [20]:
# Ejercicio 2

stock = np.array(
    [
        [25, 18, 30, 12, 20], 
        [14, 22, 16, 28, 19], 
        [35, 17, 24, 15, 21]
    ]
) 

ventas = np.array(
    [
        [10, 20, 12, 8, 7], 
        [16, 10, 18, 9, 20], 
        [15, 19, 8, 17, 11]
    ]
)

# Actividades

# 1. Calcula el inventario restante mediante una operación entre matrices.
stock_restante = stock - ventas
print(stock_restante)
print('-' * 100)

# 2. Localiza los valores negativos, que representan ventas mayores al stock disponible.
# print(stock_restante < 0)

mascara = stock_restante < 0
print(stock_restante[mascara])
print('-' * 100)

# 3. Crea una copia corregida en la que los valores negativos sean reemplazados por 0.
stock_restante_corregido = stock_restante.copy()
stock_restante_corregido[mascara] = 0
print(stock_restante_corregido)
print('-' * 100)

# 4. Calcula el stock restante total por categoría antes y después de la corrección.
stock_restante_antes = stock_restante.sum(axis=1)
print(stock_restante_antes)
print('-' * 100)

stock_restante_despues= stock_restante.sum(axis=0)
print(stock_restante_despues)
print('-' * 100)

# 5. Determina la categoría con mayor stock disponible después de la corrección.
print(stock_restante_despues.argmax() + 1)


[[15 -2 18  4 13]
 [-2 12 -2 19 -1]
 [20 -2 16 -2 10]]
----------------------------------------------------------------------------------------------------
[-2 -2 -2 -1 -2 -2]
----------------------------------------------------------------------------------------------------
[[15  0 18  4 13]
 [ 0 12  0 19  0]
 [20  0 16  0 10]]
----------------------------------------------------------------------------------------------------
[48 26 42]
----------------------------------------------------------------------------------------------------
[33  8 32 21 22]
----------------------------------------------------------------------------------------------------
1


In [37]:
# Ejercicio 3
# array[sucursal, producto]
precios = np.array([[4.5, 6.0, 3.5, 8.0], 
                    [4.7, 5.8, 3.6, 8.2], 
                    [4.6, 6.1, 3.4, 7.9]]) 

unidades = np.array([[30, 18, 42, 15], 
                     [25, 20, 35, 17], 
                     [28, 22, 40, 14]])


# Actividades

# 1. Calcula la facturación por producto y sucursal mediante multiplicación elemento a elemento.
total = precios  * unidades
print(total)
print('-' * 100)

# 2. Calcula la facturación total de cada sucursal y la facturación total de cada producto.
total_sucursal = total.sum(axis=1)
total_producto = total.sum(axis=0)
print(total_sucursal)
print(total_producto)
print('-' * 100)

# 3. Identifica la sucursal con mayor facturación.
print(total_sucursal.argmax() + 1)
print('-' * 100)

# 4. Encuentra el valor máximo de facturación individual y su posición dentro de la matriz.
valor_maximo = total.max()
print(valor_maximo)
print('-' * 100)

posicion_max = np.unravel_index(total.argmax(), total.shape)
print(f"Posición (Sucursal, Producto): Fila {posicion_max[0]}, Columna {posicion_max[1]}")
print('-' * 100)

# 5. Obtén la transpuesta de la matriz de facturación e interpreta qué representan ahora sus filas.
print(total.T)


[[135.  108.  147.  120. ]
 [117.5 116.  126.  139.4]
 [128.8 134.2 136.  110.6]]
----------------------------------------------------------------------------------------------------
[510.  498.9 509.6]
[381.3 358.2 409.  370. ]
----------------------------------------------------------------------------------------------------
1
----------------------------------------------------------------------------------------------------
147.0
----------------------------------------------------------------------------------------------------
Posición (Sucursal, Producto): Fila 0, Columna 2
----------------------------------------------------------------------------------------------------
[[135.  117.5 128.8]
 [108.  116.  134.2]
 [147.  126.  136. ]
 [120.  139.4 110.6]]
