In [1]:
import numpy as np

In [5]:
arr = np.arange(0, 16, 1)
matriz = arr.reshape((4,4))
print(matriz)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [6]:
matriz[1,1]

np.int64(5)

In [7]:
matriz[1,:]

array([4, 5, 6, 7])

In [8]:
matriz[:,3]

array([ 3,  7, 11, 15])

In [9]:
matriz[-1,-1]

np.int64(15)

In [11]:
vector = np.arange(0, 10, 1)
print(vector)
vista = vector[6:]
print(vista)

vista[-1] = 1000
print(vista)

[0 1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[   6    7    8 1000]


In [ ]:
vector = np.arange(0, 10, 1)
print(vector)
vista = vector[6:].copy()
print(vista)

vista[-1] = 1000
print(vista)

In [13]:
a = np.array([1.0, 4.0, 9.0])
np.clip(a,2,5)

array([2., 4., 5.])